baseURL = 'http://leonardobetti.github.io/blog/'
languageCode = 'en-uk'
title = 'Leonardo Betti'
theme = "PaperMod"
[params]
defaultTheme = "light"
disableThemeToggle = "true"

[params.homeInfoParams]
Title = "Product Designer based in London UK"
Content = "Currently working as a Product Designer for [FSB Tech](http://fsbtech.com). My focus is on designing digital products, with a specialization in creating great user experiences, developing brand identities, and building design systems. Additionally, I am an avid chess player on [Lichess](https://lichess.org) and have a keen interest in tech and design tools such as [Figma](https://www.figma.com), [Penpot](https://www.penpot.app), [PGP](https://www.openpgp.org), [Linux](https://en.wikipedia.org/wiki/Linux), and [Bitcoin](https://bitcoin.org)."

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/leonardobetti87/"

[[params.socialIcons]]
name = "email"
url = "mailto:leonardobetti@gmail.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/leonardobetti/"

[[params.socialIcons]]
name = "dribbble"
url = "https://dribbble.com/leonardobetti"
